### ISSUE TITLE
show records from selected template types

### ISSUE THREAD

**Issue by daviortega** [oipwg/oip-ddx-light#4]
it should be a filter

**Comment by orpheus** [comment]
it is.

in `config.js` there is a template filter array. 
Fill this array with template name strings (`tmpl_XXXXXXXXX`) 
then either keep the `templateOperand` as `OR` or switch it to `AND`. 

OR will filter all records that contain ANY of the templates in your template filter.

AND will filter all records that contain ALL of the templates in your template filter
