### ISSUE TITLE
wrong wraper in template grids

### ISSUE THREAD

**Issue by daviortega** [oipwg/oip-ddx-light#6]
![2019-06-11-162742_226x317_scrot](https://user-images.githubusercontent.com/2179854/59313863-7db45080-8c67-11e9-9a52-5144218b2b53.png)

**Comment by orpheus** [comment]
temporary fix: I'm hiding overflow text. you won't be able to see the full description now. Add another issue for a template card redesign which is what it'll need.

0defc76
